all: SkillModel.class TreeModel.class RequirementModel.class
	
TreeModel.class SkillModel.class RequirementModel.class:
	javac TreeModel.java SkillModel.java RequirementModel.java

clean: 
	rm -rf *.class
	rm -rf *~
	rm -rf *.sw*
